alter table admin rename column created_at_user to user_created_at;
alter table coordinator rename column created_at_user to user_created_at;
alter table student rename column created_at_user to user_created_at;
alter table teacher rename column created_at_user to user_created_at;

alter table class rename to class_group;
alter table class_group rename column id to class_group_id;
alter table class_group rename column acronym_class to acronym;
alter table class_students rename to class_group_student;
alter table class_group_student rename column class_id to class_group_id;
alter table class_group_student rename column students_id to student_id;
alter table class_teachers rename to class_group_teacher;
alter table class_group_teacher rename column classes_id to class_group_id;
alter table class_group_teacher rename column teachers_id to teacher_id;

alter table buy drop constraint if exists buy_buy_aluno_id_key;
alter table buy drop constraint if exists buy_buy_professor_id_key;
alter table buy add column class_group_id bigint;
alter table buy add column equipment_id bigint;
alter table buy drop column buy_class_group;
alter table buy drop column buy_equipment;

alter table equipment rename column equipement_price to equipment_price;
alter table equipment rename column equipement_quantity to equipment_quantity;
alter table equipment rename column equipement_sap to equipment_sap;

alter table machine drop constraint if exists fk_machine_place;
alter table machine_log drop constraint if exists fk_machine_log_machine;
alter table machine_log drop constraint if exists fk_machine_log_teacher;
alter table machine rename column machine_heritage to machine_patrimony;
alter table machine rename column machine_place_id to place_id;
alter table machine alter column machine_id type integer using machine_id::integer;
alter table machine alter column machine_created_at type date using machine_created_at::date;
alter table machine add column machine_condition varchar(255);
alter table machine add column machine_tag varchar(255);
alter table machine add column machine_last_maintenance timestamp(6);

alter table machine_log rename column machine_log_machine_id to machine_id;
alter table machine_log rename column machine_log_responsible_id to teacher_id;
alter table machine_log alter column machine_id type integer using machine_id::integer;
alter table machine_log alter column machine_log_hour_register type date using machine_log_hour_register::date;
alter table machine_log add column machine_log_content text;
alter table machine_log add column task_situation varchar(255);
alter table machine_log add column action_to_execute text;
alter table machine_log add column task_criticality varchar(255);
alter table machine_log add column image bytea;
alter table machine_log add column place_id bigint;
alter table machine_log add column maintenance_type varchar(255);
alter table machine_log add column registration_period varchar(255);
alter table machine_log add column class_id bigint;
alter table machine_log add column report_link varchar(2048);

create table autonomous_maintenance (
    autonomous_maintenance_id integer generated by default as identity primary key,
    date_time timestamp(6) not null,
    equipment_id bigint not null,
    student_id bigint not null,
    teacher_id bigint not null,
    equipment_condition varchar(255) not null check (equipment_condition in ('CONFORME', 'NAO_CONFORME')),
    equipment_situation varchar(255) not null check (equipment_situation in ('OPERANDO', 'NAO_OPERANDO')),
    identified_nonconformities text,
    patrimony varchar(255),
    tag varchar(255)
);

create table inconvenience_5s (
    inconvenience_5s_id integer generated by default as identity primary key,
    inconvenience varchar(255) not null,
    status boolean not null,
    place_id bigint not null,
    teacher_id bigint not null,
    event_date date not null,
    class_id bigint not null,
    description text,
    registered_occasion varchar(255)
);
create table inconvenience_5s_image (inconvenience_5s_id integer not null, image_url varchar(2048) not null);
create table inconvenience_5s_student (inconvenience_5s_id integer not null, student_id bigint not null);

create table machine_log_student (machine_log_id bigint not null, student_id bigint not null);

create table maintenance_request (
    maintenance_request_id integer generated by default as identity primary key,
    status varchar(255) not null check (status in ('NAO_VISUALIZADA', 'FINALIZADA', 'EM_ANALISE')),
    designation_id bigint not null,
    priority varchar(255) not null check (priority in ('ALTA', 'MEDIA', 'BAIXA')),
    place_id bigint not null,
    description text not null,
    patrimony varchar(255),
    tag varchar(255),
    created_at timestamp(6) not null,
    teacher_id bigint not null,
    machine_id integer not null
);
create table maintenance_request_image (maintenance_request_id integer not null, image_data bytea not null);
create table maintenance_request_student (maintenance_request_id integer not null, student_id bigint not null);

alter table buy add constraint fk_buy_class_group foreign key (class_group_id) references class_group;
alter table buy add constraint fk_buy_equipment foreign key (equipment_id) references equipment;
alter table machine add constraint fk_machine_place foreign key (place_id) references place;
alter table machine_log add constraint fk_machine_log_machine foreign key (machine_id) references machine;
alter table machine_log add constraint fk_machine_log_teacher foreign key (teacher_id) references teacher;
alter table machine_log add constraint fk_machine_log_place foreign key (place_id) references place;
alter table machine_log add constraint fk_machine_log_class_group foreign key (class_id) references class_group;
alter table machine_log_student add constraint fk_machine_log_student_log foreign key (machine_log_id) references machine_log;
alter table machine_log_student add constraint fk_machine_log_student_student foreign key (student_id) references student;
alter table autonomous_maintenance add constraint fk_autonomous_maintenance_equipment foreign key (equipment_id) references equipment;
alter table autonomous_maintenance add constraint fk_autonomous_maintenance_student foreign key (student_id) references student;
alter table autonomous_maintenance add constraint fk_autonomous_maintenance_teacher foreign key (teacher_id) references teacher;
alter table inconvenience_5s add constraint fk_inconvenience_5s_place foreign key (place_id) references place;
alter table inconvenience_5s add constraint fk_inconvenience_5s_teacher foreign key (teacher_id) references teacher;
alter table inconvenience_5s add constraint fk_inconvenience_5s_class_group foreign key (class_id) references class_group;
alter table inconvenience_5s_image add constraint fk_inconvenience_5s_image foreign key (inconvenience_5s_id) references inconvenience_5s;
alter table inconvenience_5s_student add constraint fk_inconvenience_5s_student_5s foreign key (inconvenience_5s_id) references inconvenience_5s;
alter table inconvenience_5s_student add constraint fk_inconvenience_5s_student_student foreign key (student_id) references student;
alter table maintenance_request add constraint fk_maintenance_request_designation foreign key (designation_id) references designation;
alter table maintenance_request add constraint fk_maintenance_request_place foreign key (place_id) references place;
alter table maintenance_request add constraint fk_maintenance_request_teacher foreign key (teacher_id) references teacher;
alter table maintenance_request add constraint fk_maintenance_request_machine foreign key (machine_id) references machine;
alter table maintenance_request_image add constraint fk_maintenance_request_image foreign key (maintenance_request_id) references maintenance_request;
alter table maintenance_request_student add constraint fk_maintenance_request_student_request foreign key (maintenance_request_id) references maintenance_request;
alter table maintenance_request_student add constraint fk_maintenance_request_student_student foreign key (student_id) references student;
