create table users (
    user_id bigint generated by default as identity primary key,
    user_name varchar(120) not null,
    user_email varchar(150) not null unique,
    user_password varchar(100) not null,
    user_role varchar(30) not null,
    user_enabled boolean not null default true,
    account_non_locked boolean not null default true,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null
);

alter table buy drop constraint if exists fk_buy_student;
alter table buy drop constraint if exists fk_buy_teacher;
alter table class_group_student drop constraint if exists fk_class_students_student;
alter table class_group_teacher drop constraint if exists fk_class_teachers_teacher;
alter table machine_log drop constraint if exists fk_machine_log_teacher;
alter table autonomous_maintenance drop constraint if exists fk_autonomous_maintenance_student;
alter table autonomous_maintenance drop constraint if exists fk_autonomous_maintenance_teacher;
alter table inconvenience_5s drop constraint if exists fk_inconvenience_5s_teacher;
alter table inconvenience_5s_student drop constraint if exists fk_inconvenience_5s_student_student;
alter table maintenance_request drop constraint if exists fk_maintenance_request_teacher;

create temporary table user_id_map (
    source_table varchar(30) not null,
    old_id bigint not null,
    new_id bigint not null,
    primary key (source_table, old_id)
);

do $$
declare
    user_row record;
    migrated_user_id bigint;
begin
    for user_row in select id, user_name, user_email, user_created_at from admin loop
        insert into users (
            user_name, user_email, user_password, user_role,
            user_enabled, account_non_locked, created_at, updated_at
        ) values (
            user_row.user_name, user_row.user_email,
            '!MIGRATE_PASSWORD_REQUIRED!', 'ADMIN',
            true, true, coalesce(user_row.user_created_at, current_timestamp),
            coalesce(user_row.user_created_at, current_timestamp)
        ) returning user_id into migrated_user_id;
        insert into user_id_map values ('admin', user_row.id, migrated_user_id);
    end loop;

    for user_row in select id, user_name, user_email, user_created_at from coordinator loop
        insert into users (
            user_name, user_email, user_password, user_role,
            user_enabled, account_non_locked, created_at, updated_at
        ) values (
            user_row.user_name, user_row.user_email,
            '!MIGRATE_PASSWORD_REQUIRED!', 'COORDENADOR',
            true, true, coalesce(user_row.user_created_at, current_timestamp),
            coalesce(user_row.user_created_at, current_timestamp)
        ) returning user_id into migrated_user_id;
        insert into user_id_map values ('coordinator', user_row.id, migrated_user_id);
    end loop;

    for user_row in select id, user_name, user_email, user_created_at from teacher loop
        insert into users (
            user_name, user_email, user_password, user_role,
            user_enabled, account_non_locked, created_at, updated_at
        ) values (
            user_row.user_name, user_row.user_email,
            '!MIGRATE_PASSWORD_REQUIRED!', 'PROFESSOR',
            true, true, coalesce(user_row.user_created_at, current_timestamp),
            coalesce(user_row.user_created_at, current_timestamp)
        ) returning user_id into migrated_user_id;
        insert into user_id_map values ('teacher', user_row.id, migrated_user_id);
    end loop;

    for user_row in select id, user_name, user_email, user_created_at from student loop
        insert into users (
            user_name, user_email, user_password, user_role,
            user_enabled, account_non_locked, created_at, updated_at
        ) values (
            user_row.user_name, user_row.user_email,
            '!MIGRATE_PASSWORD_REQUIRED!', 'ALUNO',
            true, true, coalesce(user_row.user_created_at, current_timestamp),
            coalesce(user_row.user_created_at, current_timestamp)
        ) returning user_id into migrated_user_id;
        insert into user_id_map values ('student', user_row.id, migrated_user_id);
    end loop;
end
$$;

update admin target
set id = mapping.new_id
from user_id_map mapping
where mapping.source_table = 'admin'
  and target.id = mapping.old_id;

update coordinator target
set id = mapping.new_id
from user_id_map mapping
where mapping.source_table = 'coordinator'
  and target.id = mapping.old_id;

update teacher target
set id = mapping.new_id
from user_id_map mapping
where mapping.source_table = 'teacher'
  and target.id = mapping.old_id;

update student target
set id = mapping.new_id
from user_id_map mapping
where mapping.source_table = 'student'
  and target.id = mapping.old_id;

update buy target
set buy_aluno_id = mapping.new_id
from user_id_map mapping
where mapping.source_table = 'student'
  and target.buy_aluno_id = mapping.old_id;

update buy target
set buy_professor_id = mapping.new_id
from user_id_map mapping
where mapping.source_table = 'teacher'
  and target.buy_professor_id = mapping.old_id;

update class_group_student target
set student_id = mapping.new_id
from user_id_map mapping
where mapping.source_table = 'student'
  and target.student_id = mapping.old_id;

update class_group_teacher target
set teacher_id = mapping.new_id
from user_id_map mapping
where mapping.source_table = 'teacher'
  and target.teacher_id = mapping.old_id;

update machine_log target
set teacher_id = mapping.new_id
from user_id_map mapping
where mapping.source_table = 'teacher'
  and target.teacher_id = mapping.old_id;

update autonomous_maintenance target
set student_id = mapping.new_id
from user_id_map mapping
where mapping.source_table = 'student'
  and target.student_id = mapping.old_id;

update autonomous_maintenance target
set teacher_id = mapping.new_id
from user_id_map mapping
where mapping.source_table = 'teacher'
  and target.teacher_id = mapping.old_id;

update inconvenience_5s target
set teacher_id = mapping.new_id
from user_id_map mapping
where mapping.source_table = 'teacher'
  and target.teacher_id = mapping.old_id;

update inconvenience_5s_student target
set student_id = mapping.new_id
from user_id_map mapping
where mapping.source_table = 'student'
  and target.student_id = mapping.old_id;

update maintenance_request target
set teacher_id = mapping.new_id
from user_id_map mapping
where mapping.source_table = 'teacher'
  and target.teacher_id = mapping.old_id;

alter table admin rename column id to user_id;
alter table coordinator rename column id to user_id;
alter table teacher rename column id to user_id;
alter table student rename column id to user_id;

alter table admin add constraint fk_admin_user foreign key (user_id) references users(user_id);
alter table coordinator add constraint fk_coordinator_user foreign key (user_id) references users(user_id);
alter table teacher add constraint fk_teacher_user foreign key (user_id) references users(user_id);
alter table student add constraint fk_student_user foreign key (user_id) references users(user_id);

alter table admin drop column if exists user_created_at;
alter table admin drop column if exists role_user;
alter table admin drop column if exists user_email;
alter table admin drop column if exists user_name;
alter table coordinator drop column if exists user_created_at;
alter table coordinator drop column if exists role_user;
alter table coordinator drop column if exists user_email;
alter table coordinator drop column if exists user_name;
alter table teacher drop column if exists user_created_at;
alter table teacher drop column if exists role_user;
alter table teacher drop column if exists user_email;
alter table teacher drop column if exists user_name;
alter table student drop column if exists user_created_at;
alter table student drop column if exists role_user;
alter table student drop column if exists user_email;
alter table student drop column if exists user_name;

alter table class_group drop column if exists user_created_at;
alter table class_group drop column if exists role_user;
alter table class_group drop column if exists user_email;
alter table class_group drop column if exists user_name;

alter table class_group_teacher
    add constraint fk_class_group_teacher_teacher foreign key (teacher_id) references teacher(user_id);
alter table class_group_student
    add constraint fk_class_group_student_student foreign key (student_id) references student(user_id);

alter table equipment rename column equipment_price to unit_price;
alter table equipment rename column equipment_quantity to available_quantity;
alter table equipment alter column unit_price type numeric(15,2) using unit_price::numeric(15,2);

alter table helper_material add column title varchar(150) not null default 'Legacy helper material';
alter table helper_material add column description text;
alter table helper_material add column url varchar(2048) not null default 'https://example.invalid/legacy-helper-material';
alter table helper_material add column type varchar(40) not null default 'MANUAL';
alter table helper_material alter column title drop default;
alter table helper_material alter column url drop default;
alter table helper_material alter column type drop default;

alter table machine drop constraint if exists fk_machine_place;
alter table machine alter column machine_id type bigint using machine_id::bigint;
alter table machine rename column machine_created_at to created_at;
alter table machine alter column created_at type timestamp(6) using created_at::timestamp(6);
alter table machine add constraint fk_machine_place foreign key (place_id) references place(place_id);

alter table machine_log drop constraint if exists fk_machine_log_machine;
alter table machine_log drop constraint if exists fk_machine_log_place;
alter table machine_log drop constraint if exists fk_machine_log_class_group;
alter table machine_log alter column machine_id type bigint using machine_id::bigint;
alter table machine_log rename column machine_log_title to title;
alter table machine_log rename column machine_log_description to description;
alter table machine_log rename column machine_log_content to execution_report;
alter table machine_log rename column machine_log_service_execute to service_performed;
alter table machine_log rename column machine_log_conclusion to teacher_concluded_at;
alter table machine_log rename column machine_log_hour_register to registered_at;
alter table machine_log rename column teacher_id to responsible_teacher_id;
alter table machine_log rename column action_to_execute to planned_action;
alter table machine_log rename column class_id to class_group_id;
alter table machine_log alter column registered_at type timestamp(6) using registered_at::timestamp(6);
alter table machine_log add column execution_started_at timestamp(6);
alter table machine_log add column execution_ended_at timestamp(6);
alter table machine_log add column created_by_user_id bigint;
update machine_log set registered_at = current_timestamp where registered_at is null;
alter table machine_log add constraint fk_machine_log_machine foreign key (machine_id) references machine(machine_id);
alter table machine_log add constraint fk_machine_log_place foreign key (place_id) references place(place_id);
alter table machine_log add constraint fk_machine_log_class_group foreign key (class_group_id) references class_group(class_group_id);
alter table machine_log add constraint fk_machine_log_responsible_teacher foreign key (responsible_teacher_id) references teacher(user_id);
alter table machine_log add constraint fk_machine_log_created_by foreign key (created_by_user_id) references users(user_id);

alter table autonomous_maintenance drop constraint if exists fk_autonomous_maintenance_equipment;
alter table autonomous_maintenance alter column autonomous_maintenance_id type bigint using autonomous_maintenance_id::bigint;
alter table autonomous_maintenance rename column date_time to inspected_at;
alter table autonomous_maintenance rename column equipment_id to inspected_machine_id;
alter table autonomous_maintenance rename column teacher_id to responsible_teacher_id;
alter table autonomous_maintenance rename column student_id to responsible_student_id;
alter table autonomous_maintenance add column created_by_user_id bigint;
alter table autonomous_maintenance add constraint fk_autonomous_maintenance_machine foreign key (inspected_machine_id) references machine(machine_id);
alter table autonomous_maintenance add constraint fk_autonomous_maintenance_student_user foreign key (responsible_student_id) references student(user_id);
alter table autonomous_maintenance add constraint fk_autonomous_maintenance_teacher_user foreign key (responsible_teacher_id) references teacher(user_id);
alter table autonomous_maintenance add constraint fk_autonomous_maintenance_created_by foreign key (created_by_user_id) references users(user_id);

alter table inconvenience_5s drop constraint if exists fk_inconvenience_5s_place;
alter table inconvenience_5s drop constraint if exists fk_inconvenience_5s_class_group;
alter table inconvenience_5s alter column inconvenience_5s_id type bigint using inconvenience_5s_id::bigint;
alter table inconvenience_5s alter column status type varchar(30)
    using case when status then 'NOTIFICADO' else 'NAO_VISUALIZADA' end;
alter table inconvenience_5s rename column teacher_id to notified_teacher_id;
alter table inconvenience_5s rename column event_date to created_at;
alter table inconvenience_5s rename column class_id to class_group_id;
alter table inconvenience_5s add column created_by_user_id bigint;
alter table inconvenience_5s add column registration_period varchar(30) not null default 'MATUTINO';
alter table inconvenience_5s alter column registration_period drop default;
alter table inconvenience_5s alter column created_at type timestamp(6) using created_at::timestamp(6);
alter table inconvenience_5s_student alter column inconvenience_5s_id type bigint using inconvenience_5s_id::bigint;
alter table inconvenience_5s add constraint fk_inconvenience_5s_place_new foreign key (place_id) references place(place_id);
alter table inconvenience_5s add constraint fk_inconvenience_5s_teacher_user foreign key (notified_teacher_id) references teacher(user_id);
alter table inconvenience_5s add constraint fk_inconvenience_5s_class_group_new foreign key (class_group_id) references class_group(class_group_id);
alter table inconvenience_5s add constraint fk_inconvenience_5s_created_by foreign key (created_by_user_id) references users(user_id);

alter table maintenance_request drop constraint if exists fk_maintenance_request_designation;
alter table maintenance_request drop constraint if exists fk_maintenance_request_place;
alter table maintenance_request drop constraint if exists fk_maintenance_request_machine;
alter table maintenance_request alter column maintenance_request_id type bigint using maintenance_request_id::bigint;
alter table maintenance_request alter column machine_id type bigint using machine_id::bigint;
alter table maintenance_request add column sector varchar(30);
update maintenance_request request
set sector = designation.designation_sector::text
from designation
where request.designation_id = designation.designation_id;
update maintenance_request set sector = 'AREA_NAO_DESIGNADA' where sector is null;
alter table maintenance_request alter column sector set not null;
alter table maintenance_request rename column teacher_id to notified_teacher_id;
alter table maintenance_request add column created_by_user_id bigint;
alter table maintenance_request add constraint fk_maintenance_request_place_new foreign key (place_id) references place(place_id);
alter table maintenance_request add constraint fk_maintenance_request_machine_new foreign key (machine_id) references machine(machine_id);
alter table maintenance_request add constraint fk_maintenance_request_teacher_user foreign key (notified_teacher_id) references teacher(user_id);
alter table maintenance_request add constraint fk_maintenance_request_created_by foreign key (created_by_user_id) references users(user_id);
alter table maintenance_request_student alter column maintenance_request_id type bigint using maintenance_request_id::bigint;

alter table buy drop constraint if exists fk_buy_class_group;
alter table buy drop constraint if exists fk_buy_equipment;
alter table buy alter column buy_id type bigint using buy_id::bigint;
alter table buy rename column buy_status to status_legacy;
alter table buy add column status varchar(30) not null default 'NAO_VISUALIZADO';
update buy
set status = case lower(status_legacy)
    when 'entregue' then 'ENTREGUE'
    when 'emanálise' then 'EM_ANALISE'
    when 'emanalise' then 'EM_ANALISE'
    when 'pedidoemandamento' then 'PEDIDO_EM_ANDAMENTO'
    when 'naovisualizado' then 'NAO_VISUALIZADO'
    else 'NAO_VISUALIZADO'
end;
alter table buy alter column status drop default;
alter table buy rename column buy_created_at to created_at;
alter table buy alter column created_at type timestamp(6) using created_at::timestamp(6);
alter table buy rename column buy_purchase_justification to purchase_justification;
alter table buy add column created_by_user_id bigint;
alter table buy add column notified_teacher_id bigint;
update buy target
set created_by_user_id = target.buy_aluno_id;
update buy target
set notified_teacher_id = target.buy_professor_id;
alter table buy add constraint fk_buy_created_by foreign key (created_by_user_id) references users(user_id);
alter table buy add constraint fk_buy_notified_teacher foreign key (notified_teacher_id) references teacher(user_id);
alter table buy add constraint fk_buy_class_group_new foreign key (class_group_id) references class_group(class_group_id);

create table buy_item (
    buy_item_id bigint generated by default as identity primary key,
    buy_id bigint not null,
    equipment_id bigint not null,
    quantity integer not null,
    technical_specification text,
    sap varchar(100),
    patrimony varchar(100),
    tag varchar(100),
    mechanical_set varchar(150),
    constraint fk_buy_item_buy foreign key (buy_id) references buy(buy_id),
    constraint fk_buy_item_equipment foreign key (equipment_id) references equipment(equipment_id)
);

insert into buy_item (
    buy_id, equipment_id, quantity, technical_specification,
    sap, patrimony, tag, mechanical_set
)
select buy_id, equipment_id, coalesce(buy_quantity, 1),
       buy_technical_specification, buy_sap, buy_patrimony,
       buy_tag, buy_mechanical_set
from buy
where equipment_id is not null;

create table media (
    media_id bigint generated by default as identity primary key,
    media_description varchar(255),
    media_type varchar(50) not null,
    storage_key varchar(500) not null unique,
    original_name varchar(255) not null,
    content_type varchar(100) not null,
    file_size bigint not null,
    created_at timestamp(6) not null
);

create table equipment_media (
    equipment_id bigint not null,
    media_id bigint not null unique,
    primary key (equipment_id, media_id),
    constraint fk_equipment_media_equipment foreign key (equipment_id) references equipment(equipment_id),
    constraint fk_equipment_media_media foreign key (media_id) references media(media_id)
);

create table machine_log_media (
    machine_log_id bigint not null,
    media_id bigint not null unique,
    primary key (machine_log_id, media_id),
    constraint fk_machine_log_media_log foreign key (machine_log_id) references machine_log(machine_log_id),
    constraint fk_machine_log_media_media foreign key (media_id) references media(media_id)
);

create table maintenance_request_media (
    maintenance_request_id bigint not null,
    media_id bigint not null unique,
    primary key (maintenance_request_id, media_id),
    constraint fk_maintenance_request_media_request foreign key (maintenance_request_id) references maintenance_request(maintenance_request_id),
    constraint fk_maintenance_request_media_media foreign key (media_id) references media(media_id)
);

create table autonomous_maintenance_media (
    autonomous_maintenance_id bigint not null,
    media_id bigint not null unique,
    primary key (autonomous_maintenance_id, media_id),
    constraint fk_autonomous_maintenance_media_maintenance foreign key (autonomous_maintenance_id) references autonomous_maintenance(autonomous_maintenance_id),
    constraint fk_autonomous_maintenance_media_media foreign key (media_id) references media(media_id)
);

create table inconvenience_5s_media (
    inconvenience_5s_id bigint not null,
    media_id bigint not null unique,
    primary key (inconvenience_5s_id, media_id),
    constraint fk_inconvenience_5s_media_inconvenience foreign key (inconvenience_5s_id) references inconvenience_5s(inconvenience_5s_id),
    constraint fk_inconvenience_5s_media_media foreign key (media_id) references media(media_id)
);

create table buy_media (
    buy_id bigint not null,
    media_id bigint not null unique,
    primary key (buy_id, media_id),
    constraint fk_buy_media_buy foreign key (buy_id) references buy(buy_id),
    constraint fk_buy_media_media foreign key (media_id) references media(media_id)
);

create table history_log (
    history_log_id bigint generated by default as identity primary key,
    actor_id bigint not null,
    actor_role varchar(30) not null,
    action varchar(40) not null,
    entity_type varchar(40) not null,
    entity_id bigint not null,
    description text,
    created_at timestamp(6) not null,
    constraint fk_history_log_actor foreign key (actor_id) references users(user_id)
);
