 create table notification (
      notification_id bigint generated by default as identity primary key,
      notification_email varchar(150) not null,
      notification_title varchar(150) not null,
      notification_about varchar(255),
      notification_description text not null,
      notification_status_read boolean not null default false
  );

  create index idx_notification_email
      on notification (notification_email);

  create index idx_notification_status_read
      on notification (notification_status_read);
