package com.weg.Maintenance_API.enums;

public enum MaintenanceRequestStatus {
    PENDENTE_APROVACAO_PROFESSOR,
    APROVADA_PELO_PROFESSOR,
    REPROVADA_PELO_PROFESSOR,
    PENDENTE_APROVACAO_COORDENADOR,
    APROVADA_PELO_COORDENADOR,
    REPROVADA_PELO_COORDENADOR,
    NAO_VISUALIZADA,
    FINALIZADA,
    EM_ANALISE
}
